using System.Text.Json;
using Microsoft.Extensions.Options;
using Nexus.Spoke.Models;

namespace Nexus.Spoke.Services;

public class ProjectManager(
    IOptions<SpokeConfiguration> config,
    IHubConnectionService hubConnection,
    ILogger<ProjectManager> logger) : IProjectManager
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    private static readonly Dictionary<ProjectStatus, ProjectStatus[]> ValidTransitions = new()
    {
        [ProjectStatus.Planning] = [ProjectStatus.Active],
        [ProjectStatus.Active] = [ProjectStatus.Paused, ProjectStatus.Completed, ProjectStatus.Failed],
        [ProjectStatus.Paused] = [ProjectStatus.Active, ProjectStatus.Failed],
        [ProjectStatus.Completed] = [],
        [ProjectStatus.Failed] = []
    };

    public async Task<ProjectInfo> CreateProjectAsync(string projectKey, string? name = null, string? summary = null)
    {
        ValidateProjectKey(projectKey);
        var projectPath = GetProjectPath(projectKey);

        if (Directory.Exists(projectPath))
        {
            logger.LogDebug("Project {ProjectKey} already exists, returning existing", projectKey);
            var existing = await GetProjectAsync(projectKey);
            if (existing is not null) return existing;
        }

        Directory.CreateDirectory(projectPath);
        Directory.CreateDirectory(Path.Combine(projectPath, ".meta"));
        Directory.CreateDirectory(Path.Combine(projectPath, "jobs"));

        var now = DateTimeOffset.UtcNow;
        var status = new StatusMetadata(ProjectStatus.Planning, now, now, []);
        await WriteJsonAsync(Path.Combine(projectPath, ".meta", "status.json"), status);

        await File.WriteAllTextAsync(
            Path.Combine(projectPath, ".meta", "context.md"),
            $"# {name ?? projectKey}\n\nProject context will be assembled here.\n");

        await File.WriteAllTextAsync(
            Path.Combine(projectPath, ".meta", "plan.md"),
            $"# Implementation Plan\n\nPlan will be generated by the agent.\n");

        logger.LogInformation("Created project {ProjectKey} at {Path}", projectKey, projectPath);

        return new ProjectInfo(projectKey, name ?? projectKey, ProjectStatus.Planning, now, now, summary, projectKey);
    }

    public async Task<ProjectInfo?> GetProjectAsync(string projectKey)
    {
        ValidateProjectKey(projectKey);
        var statusPath = Path.Combine(GetMetaPath(projectKey), "status.json");
        if (!File.Exists(statusPath)) return null;

        var statusJson = await File.ReadAllTextAsync(statusPath);
        var status = JsonSerializer.Deserialize<StatusMetadata>(statusJson, JsonOptions);
        if (status is null) return null;

        string? ticketSummary = null;
        string? ticketName = null;
        var ticketPath = Path.Combine(GetMetaPath(projectKey), "ticket.json");
        if (File.Exists(ticketPath))
        {
            var ticketJson = await File.ReadAllTextAsync(ticketPath);
            var ticket = JsonSerializer.Deserialize<TicketMetadata>(ticketJson, JsonOptions);
            ticketSummary = ticket?.Description;
            ticketName = ticket?.Summary;
        }

        return new ProjectInfo(
            projectKey,
            ticketName ?? projectKey,
            status.Status,
            status.CreatedAt,
            status.UpdatedAt,
            ticketSummary,
            projectKey
        );
    }

    public async Task<IReadOnlyList<ProjectInfo>> ListProjectsAsync(ProjectStatus? statusFilter = null)
    {
        var projectsDir = GetProjectsDirectory();
        if (!Directory.Exists(projectsDir)) return [];

        var projects = new List<ProjectInfo>();
        foreach (var dir in Directory.GetDirectories(projectsDir))
        {
            var key = Path.GetFileName(dir);
            var project = await GetProjectAsync(key);
            if (project is null) continue;
            if (statusFilter.HasValue && project.Status != statusFilter.Value) continue;
            projects.Add(project);
        }

        return projects.OrderByDescending(p => p.UpdatedAt).ToList();
    }

    public async Task UpdateStatusAsync(string projectKey, ProjectStatus newStatus)
    {
        ValidateProjectKey(projectKey);
        var statusPath = Path.Combine(GetMetaPath(projectKey), "status.json");
        if (!File.Exists(statusPath))
            throw new InvalidOperationException($"Project {projectKey} does not exist.");

        var statusJson = await File.ReadAllTextAsync(statusPath);
        var status = JsonSerializer.Deserialize<StatusMetadata>(statusJson, JsonOptions)
            ?? throw new InvalidOperationException($"Corrupt status.json for project {projectKey}.");

        if (!ValidTransitions.TryGetValue(status.Status, out var allowed) || !allowed.Contains(newStatus))
            throw new InvalidOperationException(
                $"Invalid status transition: {status.Status} → {newStatus} for project {projectKey}.");

        var history = new List<StatusHistoryEntry>(status.History)
        {
            new(status.Status, newStatus, DateTimeOffset.UtcNow)
        };

        var updated = new StatusMetadata(newStatus, status.CreatedAt, DateTimeOffset.UtcNow, history);
        await WriteJsonAsync(statusPath, updated);

        logger.LogInformation("Project {ProjectKey} status changed: {Old} → {New}", projectKey, status.Status, newStatus);

        // Best-effort hub notification — don't let notification failures affect status persistence
        if (hubConnection.IsConnected && hubConnection.SpokeId.HasValue)
        {
            try
            {
                await hubConnection.SendAsync("ReportProjectStatusChanged",
                    new { ProjectId = hubConnection.SpokeId.Value, NewStatus = newStatus }, default);
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Failed to notify hub of status change for project {ProjectKey}", projectKey);
            }
        }
    }

    public async Task SaveTicketMetadataAsync(string projectKey, TicketMetadata ticket)
    {
        ValidateProjectKey(projectKey);
        var ticketPath = Path.Combine(GetMetaPath(projectKey), "ticket.json");
        await WriteJsonAsync(ticketPath, ticket);
        logger.LogDebug("Saved ticket metadata for {ProjectKey}", projectKey);
    }

    public string GetProjectPath(string projectKey)
    {
        ValidateProjectKey(projectKey);
        return Path.Combine(GetProjectsDirectory(), projectKey);
    }

    public string GetMetaPath(string projectKey) =>
        Path.Combine(GetProjectPath(projectKey), ".meta");

    private string GetProjectsDirectory() =>
        Path.Combine(WorkspaceInitializer.ResolveBasePath(config.Value), "projects");

    private static void ValidateProjectKey(string projectKey)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(projectKey);

        if (Path.IsPathRooted(projectKey) ||
            projectKey.Contains(Path.DirectorySeparatorChar) ||
            projectKey.Contains(Path.AltDirectorySeparatorChar) ||
            projectKey.Contains(".."))
        {
            throw new ArgumentException($"Invalid project key: '{projectKey}'. Must be a simple directory name.", nameof(projectKey));
        }
    }

    private static async Task WriteJsonAsync<T>(string path, T value)
    {
        var json = JsonSerializer.Serialize(value, JsonOptions);
        await File.WriteAllTextAsync(path, json);
    }
}
