using System.Text;
using Microsoft.Extensions.Options;
using Nexus.Spoke.Models;

namespace Nexus.Spoke.Services;

public class PromptAssembler(
    ISkillSelector skillSelector,
    IProjectHistoryInjector historyInjector,
    IOptions<SpokeConfiguration> config,
    ILogger<PromptAssembler> logger) : IPromptAssembler
{
    private const int MaxPromptChars = 50_000;

    private const string FallbackTemplate = """
        # Worker Prompt

        ## Task

        {HUB_CONTEXT}

        ## Ticket: {TICKET_KEY}

        {TICKET_DESCRIPTION}

        ## Acceptance Criteria

        {ACCEPTANCE_CRITERIA}
        """;

    public async Task<string> AssembleAsync(PromptAssemblyContext context, CancellationToken cancellationToken = default)
    {
        var template = await LoadTemplateAsync(cancellationToken);

        // Build replacement values
        var ticket = context.Ticket;
        var acceptanceCriteria = FormatAcceptanceCriteria(ticket?.AcceptanceCriteria);
        var planContent = FormatPlanContent(context.PlanMd);

        // Gather async sections in parallel
        var skillsTask = skillSelector.SelectAndSummarizeAsync(
            context.SpokeSkillsPath,
            context.ProjectSkillsPath,
            context.JobType,
            ticket?.Description ?? context.HubContext,
            cancellationToken);

        var historyTask = historyInjector.GetHistorySummaryAsync(
            context.ProjectKey,
            context.JobId,
            cancellationToken: cancellationToken);

        await Task.WhenAll(skillsTask, historyTask);

        var skillGuidance = await skillsTask;
        var projectHistory = await historyTask;

        // Replace all placeholders
        var result = template
            .Replace("{JOB_ID}", context.JobId.ToString())
            .Replace("{JOB_TYPE}", context.JobType.ToString())
            .Replace("{PROJECT_KEY}", context.ProjectKey)
            .Replace("{TICKET_KEY}", ticket?.Key ?? string.Empty)
            .Replace("{TICKET_SUMMARY}", ticket?.Summary ?? string.Empty)
            .Replace("{TICKET_DESCRIPTION}", ticket?.Description ?? context.HubContext)
            .Replace("{ACCEPTANCE_CRITERIA}", acceptanceCriteria)
            .Replace("{ISSUE_TYPE}", ticket?.IssueType ?? string.Empty)
            .Replace("{PROJECT_CONTEXT}", context.ProjectContextMd ?? string.Empty)
            .Replace("{IMPLEMENTATION_PLAN}", planContent)
            .Replace("{PROJECT_HISTORY}", projectHistory)
            .Replace("{SKILL_GUIDANCE}", skillGuidance)
            .Replace("{HUB_CONTEXT}", context.HubContext)
            .Replace("{TIMESTAMP}", DateTimeOffset.UtcNow.ToString("o"));

        // Budget enforcement — truncate expandable sections if over limit
        if (result.Length > MaxPromptChars)
            result = EnforceBudget(result, projectHistory, skillGuidance, planContent);

        return result;
    }

    private async Task<string> LoadTemplateAsync(CancellationToken cancellationToken)
    {
        var basePath = WorkspaceInitializer.ResolveBasePath(config.Value);
        var templatePath = Path.Combine(basePath, "templates", "worker-prompt-base.md");

        if (File.Exists(templatePath))
        {
            try
            {
                return await File.ReadAllTextAsync(templatePath, cancellationToken);
            }
            catch (IOException ex)
            {
                logger.LogWarning(ex, "Failed to read template at {Path}, using fallback", templatePath);
            }
        }
        else
        {
            logger.LogWarning("Template not found at {Path}, using fallback", templatePath);
        }

        return FallbackTemplate;
    }

    private static string FormatAcceptanceCriteria(string[]? criteria)
    {
        if (criteria is null || criteria.Length == 0)
            return string.Empty;

        var sb = new StringBuilder();
        foreach (var item in criteria)
            sb.AppendLine($"- [ ] {item}");

        return sb.ToString().TrimEnd();
    }

    private static string FormatPlanContent(string? planMd)
    {
        if (string.IsNullOrWhiteSpace(planMd))
            return string.Empty;

        // Skip the default stub content
        if (planMd.Contains("Plan will be generated by the agent."))
            return string.Empty;

        return planMd;
    }

    private string EnforceBudget(string result, string history, string skills, string plan)
    {
        var overBy = result.Length - MaxPromptChars;
        logger.LogWarning("Assembled prompt is {Over} chars over budget ({Total} total), truncating", overBy, result.Length);

        // Truncate in priority order: history first, then skills, then plan
        if (!string.IsNullOrEmpty(history) && overBy > 0)
        {
            var truncated = TruncateSection(history, Math.Max(0, history.Length - overBy));
            result = result.Replace(history, truncated);
            overBy = result.Length - MaxPromptChars;
        }

        if (!string.IsNullOrEmpty(skills) && overBy > 0)
        {
            var truncated = TruncateSection(skills, Math.Max(0, skills.Length - overBy));
            result = result.Replace(skills, truncated);
            overBy = result.Length - MaxPromptChars;
        }

        if (!string.IsNullOrEmpty(plan) && overBy > 0)
        {
            var truncated = TruncateSection(plan, Math.Max(0, plan.Length - overBy));
            result = result.Replace(plan, truncated);
        }

        return result;
    }

    private static string TruncateSection(string section, int targetLength)
    {
        if (targetLength <= 0)
            return "[...truncated for prompt budget]";

        if (section.Length <= targetLength)
            return section;

        return section[..targetLength] + "\n[...truncated for prompt budget]";
    }
}
